#!/usr/bin/env python3

"""
Unified skull-strip + brain-median renormalization for PET SUVR.

Features:
- Accept SUVR image and a brain mask (subject MNI brain)
- Resample mask to SUVR grid (nearest-neighbor)
- Morphological cleanup (closing+opening, fill holes, optional erosion)
- Optional soft mask via Gaussian blur (FWHM in mm) for smoother edges
- Apply hard and soft masking
- Optional re-normalize within-brain so the brain-masked median equals 1.0

Example:
python3 Scripts/Preprocessing/PET/03_skullstrip.py \
  --suvr /path/to/sub-XXX_SUVR_s2.nii.gz \
  --mask /path/to/FDG_PET_brainmask.nii.gz \
  --morph_iters 1 --erode_iters 1 --fwhm 2 --renorm_median

Batch mode (recursively process folders under a root; finds files by suffixes):
python3 Scripts/Preprocessing/PET/03_skullstrip.py \
  --root_dir /path/to/preprocessed/PET \
  --groups CN PD \
  --fwhm 3 --morph_iters 2 --erode_iters 0 --soft_to_hard_thresh 0.5 --renorm_median --skip_if_exists

Outputs written next to the SUVR file (or --out_dir if provided):
_maskRefined.nii.gz: binary brain mask (uint8, 0/1). It's your input mask 
    resampled to the SUVR grid, cleaned by morphology (closing→opening), optional 
        1‑voxel erosion, and hole filling. Use for hard skull‑strip or QC.

_maskSoft2.nii.gz: soft brain mask (float32, 0–1). Gaussian‑blurred version 
    of the refined mask (2 mm FWHM; number matches your --fwhm). Good for visualisation or 
        gentle edge tapering.

_SUVR_s2_brain.nii.gz: hard skull‑stripped SUVR image. Equals SUVR_s2 multiplied 
    by the refined binary mask. Best for analysis/workflows expecting sharp brain boundaries. 

_SUVR_s2_brain_soft2.nii.gz: soft skull‑stripped SUVR. SUVR_s2 multiplied by the 
    soft mask. Looks cleaner at edges; use mainly for visualisation or if you want 
        slight boundary tapering.

_SUVR_s2_brain_med1.nii.gz (only with --renorm_median): brain‑masked SUVR re‑normalized 
    so the within‑brain median equals 1.0. This removes residual global scaling bias 
        inside brain after masking. The non‑renormalized hard mask output (_brain) is also written.

Optional (with --soft_to_hard_thresh): additional rounded hard‑mask and outputs
generated by thresholding the soft mask to reduce jagged edges/spikes at the boundary:
  - _maskRounded.nii.gz
  - _SUVR_s2_brain_round.nii.gz
  - _SUVR_s2_brain_round_med1.nii.gz (if --renorm_median)

"""

import argparse
import os
import glob
import numpy as np
import nibabel as nib
from nibabel.processing import resample_from_to
from scipy.ndimage import (
	binary_closing,
	binary_opening,
	binary_fill_holes,
	binary_erosion,
	gaussian_filter,
	generate_binary_structure,
)


def fwhm_to_sigma_vox(fwhm_mm: float, vx_mm: np.ndarray) -> np.ndarray:
	return (fwhm_mm / 2.355) / vx_mm


def out_path(suvr_path: str, suffix: str, out_dir: str | None) -> str:
	base = os.path.basename(suvr_path)
	if base.endswith(".nii.gz"):
		stub = base[:-7]
	elif base.endswith(".nii"):
		stub = base[:-4]
	else:
		stub = base
	d = out_dir if out_dir else os.path.dirname(suvr_path)
	return os.path.join(d, f"{stub}{suffix}.nii.gz")


def process_one(suvr_path: str, mask_path: str, args) -> list[str]:
	img = nib.load(suvr_path)
	suvr = img.get_fdata().astype(np.float32)

	mask_img = nib.load(mask_path)
	if img.shape != mask_img.shape or not np.allclose(img.affine, mask_img.affine):
		mask_img = resample_from_to(mask_img, img, order=0)

	# Binary mask + cleanup
	mask = (mask_img.get_fdata() > 0)
	st = generate_binary_structure(3, 1)
	for _ in range(max(args.morph_iters, 0)):
		mask = binary_closing(mask, structure=st)
		mask = binary_opening(mask, structure=st)
	if args.erode_iters and args.erode_iters > 0:
		mask = binary_erosion(mask, iterations=args.erode_iters)
	mask = binary_fill_holes(mask)

	# Soft mask for visuals
	soft = mask.astype(np.float32)
	if args.fwhm and args.fwhm > 0:
		vx = np.abs(np.diag(img.affine))[:3]
		sig = fwhm_to_sigma_vox(args.fwhm, vx)
		soft = gaussian_filter(soft, sigma=sig[::-1])
		soft = np.clip(soft, 0.0, 1.0)

	# Apply masks
	hard_basic = suvr * mask.astype(np.float32)
	soft_applied = suvr * soft

	# Optional re-normalization inside brain (kept as separate output)
	hard_med1 = None
	if args.renorm_median:
		vals = hard_basic[mask]
		med = float(np.median(vals)) if vals.size else 1.0
		hard_med1 = hard_basic / (med + 1e-8)

	# Optional rounded hard mask from soft mask threshold
	rounded_mask = None
	if args.soft_to_hard_thresh is not None:
		th = float(args.soft_to_hard_thresh)
		if not np.isfinite(th):
			th = 0.5
		th = min(max(th, 0.0), 1.0)
		rounded_mask = (soft >= th)
		rounded_hard = suvr * rounded_mask.astype(np.float32)

	# Write outputs next to SUVR or to out_dir (single-file mode). In batch mode, we keep next to SUVR.
	out_dir = args.out_dir if (getattr(args, "root_dir", None) is None) else None
	refined_mask_path = out_path(suvr_path, "_maskRefined", out_dir)
	soft_mask_path = out_path(suvr_path, f"_maskSoft{int(round(args.fwhm)) if args.fwhm>0 else 0}", out_dir)
	hard_out = out_path(suvr_path, f"{args.out_suffix}", out_dir)
	soft_out = out_path(suvr_path, f"{args.out_suffix}_soft{int(round(args.fwhm)) if args.fwhm>0 else 0}", out_dir)

	nib.save(nib.Nifti1Image(mask.astype(np.uint8), img.affine, img.header), refined_mask_path)
	nib.save(nib.Nifti1Image(soft.astype(np.float32), img.affine, img.header), soft_mask_path)
	nib.save(nib.Nifti1Image(hard_basic.astype(np.float32), img.affine, img.header), hard_out)
	nib.save(nib.Nifti1Image(soft_applied.astype(np.float32), img.affine, img.header), soft_out)
	written = [refined_mask_path, soft_mask_path, hard_out, soft_out]

	if hard_med1 is not None:
		med1_out = out_path(suvr_path, f"{args.out_suffix}_med1", out_dir)
		nib.save(nib.Nifti1Image(hard_med1.astype(np.float32), img.affine, img.header), med1_out)
		written.append(med1_out)

	if rounded_mask is not None:
		rounded_mask_path = out_path(suvr_path, "_maskRounded", out_dir)
		nib.save(nib.Nifti1Image(rounded_mask.astype(np.uint8), img.affine, img.header), rounded_mask_path)
		written.append(rounded_mask_path)
		rounded_out = out_path(suvr_path, f"{args.out_suffix}_round", out_dir)
		nib.save(nib.Nifti1Image(rounded_hard.astype(np.float32), img.affine, img.header), rounded_out)
		written.append(rounded_out)
		if hard_med1 is not None:
			vals_r = rounded_hard[rounded_mask]
			med_r = float(np.median(vals_r)) if vals_r.size else 1.0
			rounded_med1 = rounded_hard / (med_r + 1e-8)
			rounded_med1_out = out_path(suvr_path, f"{args.out_suffix}_round_med1", out_dir)
			nib.save(nib.Nifti1Image(rounded_med1.astype(np.float32), img.affine, img.header), rounded_med1_out)
			written.append(rounded_med1_out)

	return written


def main():
	parser = argparse.ArgumentParser(description="Skull-strip SUVR using refined brain mask and optional median renorm")
	parser.add_argument("--suvr", required=True, help="Path to SUVR image (e.g., *_SUVR_s2.nii.gz)")
	parser.add_argument("--mask", required=True, help="Path to brain mask image (subject MNI brain)")
	parser.add_argument("--out_dir", default=None, help="Optional output directory (defaults to SUVR directory)")
	parser.add_argument("--morph_iters", type=int, default=1, help="Morphology iterations (closing+opening)")
	parser.add_argument("--erode_iters", type=int, default=1, help="Additional erosion iterations after cleanup")
	parser.add_argument("--fwhm", type=float, default=2.0, help="Soft-mask blur FWHM mm (0 disables)")
	parser.add_argument("--renorm_median", action="store_true", help="Re-normalize brain voxels so median==1.0")
	parser.add_argument("--out_suffix", default="_brain", help="Suffix for masked outputs")
	parser.add_argument("--soft_to_hard_thresh", type=float, default=None, help="If set in [0,1], threshold the soft mask at this value to create a rounder hard mask and write *_maskRounded and *_<suffix>_round outputs")
	# Batch mode
	parser.add_argument("--root_dir", default=None, help="Root containing group folders (e.g., CN, PD) with subject subfolders. If set, batch mode is used and --suvr/--mask are ignored.")
	parser.add_argument("--groups", nargs="*", default=None, help="Optional list of group folder names to include (e.g., CN PD). Default: all groups found.")
	parser.add_argument("--skip_if_exists", action="store_true", help="Skip subject if the main output already exists.")
	args = parser.parse_args()

	# Batch mode
	if args.root_dir:
		if args.out_dir:
			print("[INFO] --out_dir is ignored in batch mode; outputs are written next to each SUVR file.")
		root = args.root_dir
		groups = args.groups
		processed = 0
		skipped = 0
		errors = 0
		for group_dir in sorted([d for d in glob.glob(os.path.join(root, "*")) if os.path.isdir(d)]):
			group_name = os.path.basename(group_dir)
			if groups and group_name not in set(groups):
				continue
			for subj_dir in sorted([d for d in glob.glob(os.path.join(group_dir, "*")) if os.path.isdir(d)]):
				suvrs = sorted(glob.glob(os.path.join(subj_dir, "*_SUVR_s2.nii.gz")))
				masks = sorted(glob.glob(os.path.join(subj_dir, "*_MNI_brain.nii.gz")))
				if not suvrs or not masks:
					print(f"[WARN] Missing SUVR or mask in {subj_dir}; skipping")
					continue
				suvr_path = suvrs[0]
				mask_path = masks[0]
				if args.skip_if_exists:
					expected = out_path(suvr_path, f"{args.out_suffix}", None)
					if os.path.exists(expected):
						print(f"[SKIP] {os.path.basename(subj_dir)} (exists: {os.path.basename(expected)})")
						skipped += 1
						continue
				try:
					written = process_one(suvr_path, mask_path, args)
					print(f"[OK] {os.path.basename(subj_dir)} -> {len(written)} files")
					processed += 1
				except Exception as e:
					print(f"[ERR] {os.path.basename(subj_dir)}: {e}")
					errors += 1
		print(f"Done. processed:{processed} skipped:{skipped} errors:{errors}")
		return

	# Single-file mode
	written = process_one(args.suvr, args.mask, args)
	print("Wrote:", *written)


if __name__ == "__main__":
	main()